### ISSUE TITLE
Not working - iPad Pro M1

### ISSUE THREAD

**Issue by ksignorini** [Plushtoast/ipadviewportfix#1]
It doesn't do anything on iPad Pro with M1. Viewport looks the same before/after pressing the iOS Fix button.

**Comment by Plushtoast** [comment]
The button only sets the performance mode to low which will remove the black overlay on the canvas.

The viewport should be ok by default.

Did you read this in the Readme?

* You can start Foundry in Full screen if you add it to the home screen by clicking on the share button in the browser.
* Sometimes the viewport is bugged nevertheless you can fix this by tapping in and out of the app.

On what game system did it not work? I'll have a look. Could also be system dependend.

**Comment by ksignorini** [comment]
I’ll see if I can post pics later. 

Try PF2e with Pathfinder UI v3 module.

**Comment by ksignorini** [comment]
Here are two screenshots without the Pathfinder UI v3 module enabled--just the default PF2e ui. I did these in both regular display mode and "More Space" display mode on M1 iPad Pro. Neither seems to size properly.

![IMG_0261](https://github.com/Plushtoast/ipadviewportfix/assets/6867660/3249fbbc-b92e-4d26-8194-ecb5e0dd659c)
![IMG_0260](https://github.com/Plushtoast/ipadviewportfix/assets/6867660/d9f2e57b-71ad-4d70-a2b7-9e06d5f3f88c)

**Comment by ksignorini** [comment]
Any further thoughts on a solution?

**Comment by mummson** [comment]
It stopped working for me aswell, could it be some other module that is breaking it?

**Comment by Plushtoast** [comment]
I can only look into this in a week or so, sorry

**Comment by Plushtoast** [comment]
Ok, I finally found some time to fix this. Sorry for the wait.

Let me know if there are more issues.
